//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineChat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class loginForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loginForm()
        {
            this.MEsaages = new HashSet<MEsaage>();
        }
    
        public int Log_id { get; set; }
        [Required(ErrorMessage ="Plese fill it")]

        public string Name { get; set; }
        [Required(ErrorMessage = "Plese fill it")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Plese fill it")]
        public string Pass { get; set; }
        [Required(ErrorMessage = "Plese fill it")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEsaage> MEsaages { get; set; }
    }
}
