//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEsaage
    {
        public int id { get; set; }
        public Nullable<int> UserName { get; set; }
        public string texts { get; set; }
        public Nullable<System.DateTime> whens { get; set; }
    
        public virtual loginForm loginForm { get; set; }
    }
}
