//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Messenger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversation_reply
    {
        public int cr_id { get; set; }
        public string reply { get; set; }
        public int user_id_fk { get; set; }
        public string ip { get; set; }
        public int times { get; set; }
        public int c_id_fk { get; set; }
    
        public virtual conversation conversation { get; set; }
        public virtual user user { get; set; }
    }
}
