//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Messenger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conversation()
        {
            this.conversation_reply = new HashSet<conversation_reply>();
        }
    
        public int c_id { get; set; }
        public int user_one { get; set; }
        public int user_two { get; set; }
        public string ip { get; set; }
        public Nullable<int> times { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conversation_reply> conversation_reply { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
