//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab11and12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int Friend_Id { get; set; }
        public string friend_Name { get; set; }
        public string Friend_place { get; set; }
    }
}
