//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Signup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Signup()
        {
            this.Mesages = new HashSet<Mesage>();
        }
    
        public int sig_id { get; set; }
        [Required(ErrorMessage ="Plz Enter the User Name")]
        public string sig_username { get; set; }
        [Required(ErrorMessage = "Plz Enter the  Name")]
        public string sig_Name { get; set; }
        [Required(ErrorMessage = "Plz Enter the Father Name")]
        public string sig_fname { get; set; }
        [Required(ErrorMessage = "Plz Enter the Gender")]
        public string sig_Gender { get; set; }
        [Required(ErrorMessage = "Plz Enter the Email")]
        public string sig_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesage> Mesages { get; set; }
    }
}
